sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    access-key-id: LTAI5t9xGByDV3iaLSJ5ZouJ
    access-key-secret: M0TgLTuC5iDmq1gySeYRUxkDuiFAKR
    bucket-name: sky-take-out-vic
    endpoint: oss-cn-beijing.aliyuncs.com
